### ISSUE TITLE
숙소배치 관련 요청사항

### ISSUE THREAD

**Issue by peacekim3** [INTERCP/missioncamp#10]
*작성자: 김창현 (요청 : 청대청직선캠 숙소배치 팀장 황진숙간사님) 
*적용 희망 기한: 2017년 12월 27일 (가능한 빨리)

청대청직 크로스- '등록대'에서는 신청한 인원 전체명단이 다 뜨는데 
'숙소배치'에서는 명단이 50명밖에 안뜹니다. 여기에도 전체 신청자 명단이 바로 떠서 
숙소배치팀에서 바로 배치를 할수있도록 조치를 부탁드립니다.

**Comment by esanzy** [comment]
작업 완료
