### ISSUE TITLE
청대-크로스-숙소현황 상에서 오류건 수정요청

### ISSUE THREAD

**Issue by peacekim3** [INTERCP/missioncamp#13]
작성자 : 김창현(청대선캠 숙소배치 팀장 황진숙 요청) 
희망기간 : 12/28(수;선캠 첫째날) 오전 중 

증상 : 숙소현황-> 미션룸에 116명이 배치됐는데 세부인원은 50명만 명단이 뜹니다 
확인해주시고 오류 수정 부탁드립니다. 
감사합니다

**Comment by esanzy** [comment]
조치 완료하였습니다.
