### ISSUE TITLE
☆전세대 선캠 홈피 및 크로스- 단체등록 아이디 사라지는 오류건

### ISSUE THREAD

**Issue by peacekim3** [INTERCP/missioncamp#15]
*작성자 : 김창현 (모든 선캠에 적용 요청) 
*적용 희망 기한 : 12/31 까지(가능한 빠른 시일 내 ) 

<증상>
  선캠 홈피를 통해 '단체 등록된 아이디'를
1. 해당 선캠 홈페이지에서 '단체정보수정(이름/담당자/비번 등)' 할 경우,
2. 크로스 상에서 '단체수정(이름/담당자/신청정보,비번  등 ) ' 할 경우
=> 1 or 2번 중 어떤 작업을 하든지 작업 직후,

(1) 해당 선캠 홈페이지에서 그 단체 아이디/비번을 올바르게 입력해도 '신청 조회가 안됨'
(2) 해당 선캠 크로스에서 그 단체 아이디 정보는 뜨지만 '아이디가 뭔지가 안뜸'
=> 두 가지 증상이 모두 나타나게됨

<이런 일이 발생할 시에>
해당 단체에서 담당자가 다시 아이디를 만들든지, 사이버팀 통해 해당 아이디 복구를 해드려야하기 때문에 상호 간에 많이 번거롭습니다.

**Comment by esanzy** [comment]
조치되었습니다.

**Comment by peacekim3** [comment]
전 세대 선캠홈피/크로스에서 확인완료됐습니다^^
