### ISSUE TITLE
청소년/어린이선캠- 크로스->숙소배치 오류

### ISSUE THREAD

**Issue by peacekim3** [INTERCP/missioncamp#16]
작성자 : 김창현
작업 희망기한 : 12/28(수) 가능한 

증상 : 청소년/어린이선캠 크로스에서 숙소배치를 들어가면 
Internal Server Error 라고 뜹니다. 
확인 및 복구 부탁드립니다.

**Comment by esanzy** [comment]
조치 완료하였습니다.

**Comment by peacekim3** [comment]
네 확인했습니다 감사합니다
