### ISSUE TITLE
청소년선캠-아이디 복구건(아래 글보다 우선)

### ISSUE THREAD

**Issue by peacekim3** [INTERCP/missioncamp#20]
*작성자: 김창현 (요청 : 청선캠 숙소배치 이현주 간사님)
*적용 희망 기한: 2017년 12월 29일 (가능한 빨리)

(1) 이전에 만들었던 아이디인데- 아이디 조회가 안됩니다(선캠홈피+크로스 둘다)
    17청소년MIT (youthmit17 / 1040) 
   => 복구 부탁드립니다.

(2) 고등학생/ 17청소년MIT / 010-2786-6256 인데- 이름이 안뜨는 등록자가 있습니다. 
   => (1)이 해결이 안되어 '성별이 N인 것을 수정할 수가 없습니다' 복구 부탁드립니다. 
        원래 등록자 정보는 (화성/ 김은지/ 여자) 라고 합니다. 

※ (2)가 해결되면 아래글에서 말씀드렸던 '청선캠 전체 엑셀 다운로드'가 가능할것 같습니다.

**Comment by esanzy** [comment]
조치했습니다

**Comment by peacekim3** [comment]
네 둘다 잘됩니다- 감사합니다ㅠ
