### ISSUE TITLE
청대선캠 홈피에서 단체 아이디 조회 안되는것 

### ISSUE THREAD

**Issue by peacekim3** [INTERCP/missioncamp#9]
구미송정교회 jung1234 
지금 구미 송정교회라는 이름이 두개가 있는데 둘다 
아이디 조회가 안뜨고 크로스에서도 단체등록에서 구미송정교회 조회해보면 아이디가 안뜸
아이디 조회가 가능하게되면 신청자들을  한 아이디로 몰아서 계속 사용할 예정

**Comment by esanzy** [comment]
아이디 한개는 jung1234로, 다른 한개는 jung1234_1로 복구했습니다. 비번은 모르겠네요.

**Comment by peacekim3** [comment]
네 확인했습니다
